#!/bin/bash

set -eEuo pipefail

NOW=$(date +%y%m%d_%H%M)
IMG=registry.kelly.direct/tssb-cli:latest
DATA_DIR=/mnt/wd6/tssb-daily-csvs

script=$(realpath ${1})
script_dir=$(dirname ${script})
result_file=${script}.result.${NOW}

if [ ! -f "${script}" ]; then
  echo "Error: ${script} not found"
  exit 1
fi

rm -f ${script_dir}/AUDIT.LOG

docker run \
    -it \
    --rm \
    -v ${DATA_DIR}:/root/.wine/drive_c/tssb-data/:ro \
    -v ${script_dir}:/root/.wine/drive_c/tssb-scripts/ \
    ${IMG} c:\\tssb-scripts\\$(basename ${script}) 2>&1 | tee ${script_dir}/tssb-cli.log

echo "--->tssb script<---" >> ${result_file}
cat ${script} >> ${result_file}
echo "---<tssb script>---" >> ${result_file} 
cat ${script_dir}/AUDIT.LOG >> ${result_file}
